version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    firsttest:
      image: deephdc/deep-oc-firsttest
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    firsttest-gpu:
      image: deephdc/deep-oc-firsttest:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    firsttest-rclone:
      extends:
        service: firsttest
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
